### ISSUE TITLE
ENOENT: no such file or directory in `os.tmpDir()`

### ISSUE THREAD

**Issue by manakor** [m4nuC/async-busboy#1]
**Only sometimes** when sending files via `multipart/form-data` and uploading them to S3 I am getting the following error:
````bash
Uncaught Error: ENOENT: no such file or directory, open '/var/folders/fh/w1h08fy12fngm0x499_3xr300000gn/T/filename.jpg'
      at Error (native)
````

When I log `files` variable, it always lists all files as `ReadStream`s with `path` set to `/var/folders/fh/w1h08fy12fngm0x499_3xr300000gn/T/filename.jpg`, however. Plus, when I do `ls -la /var/folders/fh/w1h08fy12fngm0x499_3xr300000gn/T/` on a `os.tmpDir()` dir afterwards, desired files exist inside:
````js
const { files, fields } = await asyncBusboy(ctx.req)
````

Wondering whether `async-busboy` causing the issue when creating `ReadStream`s or something with Promises I use for uploading files to S3…
The issue happens only sometimes. Most of the times, uploading is works successfully.

**Comment by manakor** [comment]
Have tried to debug a little more, and found out that the issue is happening before I do any uploading to S3. When logging `ReadStream`s from `files` array, I get some with an empty `buffer` (see first `ReadStream` in the example below):

````bash
[ReadStream {
   _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 65536,
     buffer: [],
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: false,
     sync: true,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events:
   { end: [Function],
     open: { [Function: g] listener: [Function: close] } },
  _eventsCount: 2,
  _maxListeners: undefined,
  path: '/var/folders/fh/w1h08fy12fngm0x499_3xr300000gn/T/1461446649726files174659 copy.jpg',
  fd: null,
  flags: 'r',
  mode: 438,
  start: undefined,
  end: undefined,
  autoClose: true,
  pos: undefined,
  fieldname: 'files',
  filename: '174659 copy.jpg',
  encoding: '7bit',
  transferEncoding: '7bit',
  mime: 'image/jpeg',
  mimeType: 'image/jpeg',
  destroyed: true

}, ReadStream {
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 65536,
     buffer: [ <Buffer ff d8 ff e1 23 a8 45 78 69 66 00 00 49 49 2a 00 08 00 ... > ],
     length: 58676,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: true,
     endEmitted: false,
     reading: false,
     sync: false,
     needReadable: false,
     emittedReadable: true,
     readableListening: false,
     resumeScheduled: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events: { end: [Function] },
  _eventsCount: 1,
  _maxListeners: undefined,
  path: '/var/folders/fh/w1h08fy12fngm0x499_3xr300000gn/T/1461446650318filesJANA8828-logo.jpg',
  fd: 35,
  flags: 'r',
  mode: 438,
  start: undefined,
  end: undefined,
  autoClose: true,
  pos: undefined,
  fieldname: 'files',
  filename: 'JANA8828-logo.jpg',
  encoding: '7bit',
  transferEncoding: '7bit',
  mime: 'image/jpeg',
  mimeType: 'image/jpeg'
}]
````

Also interesting to notice, that first `ReadStream` from the example above has `destroyed: true` property, but the second one lacks it. Directly opposite to `buffer` property values.

Probably, means the problem is inside `async-busboy` or inside `busboy` itself.

**Comment by m4nuC** [comment]
@manakor Thanks for reporting! 
We have been using the library quite extensively (on stage) on Mac OSX and Ubuntu 15 without bumping into this issue so far. What OS are you running ?

**Comment by manakor** [comment]
Mac OSX 10, Nodejs 5

**Comment by m4nuC** [comment]
I've made a small fix in 0.0.6 that hopefully should solve your problem. 

Basically the code now waits that the `writeStream` is opened before creating the `readStream`. 
This should ensure that the file array always contains valid read stream. 

Check it out and let me know if that doesn't solve your issue. 

Thanks again for reporting!

**Comment by ivancortesromero** [comment]
@m4nuC do you think [this issue](https://github.com/mscdex/busboy/issues/233#issue-684897628) is related?

**Comment by m4nuC** [comment]
@ivancortesromero sorry for the delay. Will check over the weekend
