### ISSUE TITLE
can i get the file's size ?

### ISSUE THREAD

**Issue by kid-wumeng** [m4nuC/async-busboy#15]
hi, i has a question

for example:

```
{fields, files} = await asyncBusboy(ctx.req)
```

i can get the mime, path, filename and others information of files[0] but the file's size.

how to get size? is must to use the fs.stat(path) or read to buffer ?

**Comment by dominhhai** [comment]
You have to use `fs.stat(PATH)`.
`files` array includes list of file ReadStream, so you can not get the file size by using it.

**Comment by kid-wumeng** [comment]
@dominhhai ok, thanks
