### ISSUE TITLE
Only picture file may be upload successfully

### ISSUE THREAD

**Issue by xinshouke** [m4nuC/async-busboy#2]
I test the lib in koa2, I found only picture file may be upload successfully, the .txt .execl files was unable to upload successfully!  Is there options to set?  Such as file type, upload path and so on.
BTW, I have no function named checkFiles and uploadFilesToS3, so I'd commend the lines for those codes. 
Thank, please.

**Comment by m4nuC** [comment]
You should be able to upload as many files as you wish. 

Could you post an example usage of your code ?

**Comment by xinshouke** [comment]
@m4nuC the below were my codes,so thanks!
--------------------------------------------------ejs html-------------------------------------------------------
  <form id="fileupload" action="/upload/" method="POST" enctype="multipart/form-data">
    <input id="uploadedfile" name="uploadedfile" type="file" /> 
    <button id='btn4' type="button">start upload</button>
--------------------------------------------------jquery js--------------------------------------------------------
$(function(){$('#btn4').bind("click",function(){
    console.log('uploadedfile====>',1);  
    $.ajaxFileUpload({
        url:'/upload',
        secureuri:false,
        fileElementId:'uploadedfile',
        success: function(data,status){
          console.log('data====>',data); 
          console.log('status====>',status);  
            if(typeof(data.error) != 'undefstatusined'){
                if(data.error){
                    //print error
                    alert(data.error);
                }else{
                    //clear
                    // $('#img img').attr('src',url+'cache/'+data.msg);
                }
            }
        },
        error: function(data,status,e){
          console.log('data====>',data); 
           console.log('status====>',status);  
          console.log('e====>',e);  
            //print error
            alert(e);
        }
    });
})});
----------------------------------------koa2 js in server----------------------------------
 if(ctx.url==='/upload'){
     const {files, fields} = await asyncBusboy(ctx.req);
     console.log('{files, fields}', {files, fields});

**Comment by m4nuC** [comment]
The problem comes from your upload script that uses the same *name* for all files. To debug this, open your browser network inspector (4th tab in Chrome inspector) and look at the upload request payload. Does it mountain 2 files? If not you would have to debug your upload script. (likely the `fileElementId ` parameter)

This is not an async-busboy issue.

**Comment by xinshouke** [comment]
@m4nuC Yes,it's my fault, only text file was unable to log file and filed, such as:
I code as the below:
--------------------------------------code-----------------------------------------
  const {files, fields} = await asyncBusboy(ctx.req);
  console.log('{files, fields}=====>', {files, fields});
---------------------------the infor from console while uploading txt type file------------------------
{files, fields}=====> { files: [], fields: {} }
---------------------------the infor from console while uploading other documentation--------
{files, fields}=====> { files:
   [ ReadStream {
       _readableState: [Object],
       readable: true,
       domain: null,
       _events: [Object],
       _eventsCount: 1,
       _maxListeners: undefined,
       path: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\1463019195662uploadedfile交换中心解决方案.ppt',
       fd: 6,
       flags: 'r',
       mode: 438,
       start: undefined,
       end: undefined,
       autoClose: true,
       pos: undefined,
       fieldname: 'uploadedfile',
       filename: '交换中心解决方案.ppt',
       encoding: '7bit',
       transferEncoding: '7bit',
       mime: 'application/vnd.ms-powerpoint',
       mimeType: 'application/vnd.ms-powerpoint' } ],
  fields: {} }

Would you please tell me where the cause for? please...

**Comment by m4nuC** [comment]
This again probably comes from your upload script. Text files should not make any difference. Did you upload them with the same script ?

**Comment by xinshouke** [comment]
@m4nuC yes, I used the same js file which from internet. I go through every file type, no different was found.
[ajaxfileupload.js.txt](https://github.com/m4nuC/async-busboy/files/260576/ajaxfileupload.js.txt)
