### ISSUE TITLE
TypeError: request.on is not a function

### ISSUE THREAD

**Issue by SidFeng** [m4nuC/async-busboy#28]
`
const {files, fields} = await asyncBusboy(ctx.request);
`
It's show 'TypeError: request.on is not a function'.

**Comment by m4nuC** [comment]
Sorry for the delay, did you get that issue solved? My guess is that you didn't pass the correct object to async-busboy

**Comment by octet-stream** [comment]
If it's still matter:
You've just passed wrong object to async-busboy. `ctx.request` is not the same as `ctx.req` and it not a stream at all.

@m4nuC Could you add `request` checking on top of async-bysboy function? This argument just should be an instance of `http.IncomingMessage`.

**Comment by m4nuC** [comment]
@octet-stream Thanks for pointing this out. 

I am adding the `request` checking,
