### ISSUE TITLE
filePromises not passing to custom onFile

### ISSUE THREAD

**Issue by men232** [m4nuC/async-busboy#29]
Have issue with filePromises. This arg not passing to custom onFile callback

**Comment by m4nuC** [comment]
Can you share a code sample summarising your use case ?

**Comment by men232** [comment]
It does not make sense, just look here:
```js
    // index.js
    busboy
      .on('field', onField.bind(null, fields))
      .on('file', customOnFile || onFile.bind(null, filePromises))
```

Base on your docs, filePromises should be passed to customOnFile callback.
```js
const {fields} = await asyncBusboy(ctx.req, {
    onFile: function(filePromises, fieldname, file, filename, encoding, mimetype) {
        uploadFilesToS3(file);
    }
  });
```

**Comment by m4nuC** [comment]
I am still not getting what is your issue. Can you post the actual code ?
