### ISSUE TITLE
small file can not be parsed?

### ISSUE THREAD

**Issue by wuzeru** [m4nuC/async-busboy#3]
I find a bug.

A small file which maybe 9k can not be pushed into 'files'.I debug it  and perhaps it returned before the stream was pushed into the files.

------
I get what's wrong.

![image](https://cloud.githubusercontent.com/assets/6448232/15360381/eeb0da28-1d3f-11e6-8d1a-7456a4954d37.png)

the busboy closed before the writeStream open.

so if i code like this

```
function onFile(files, fieldname, file, filename, encoding, mimetype) {
  const tmpName = file.tmpName = new Date().getTime()  + fieldname  + filename;
  const saveTo = path.join(os.tmpDir(), path.basename(tmpName));
  const writeStream = file.pipe(fs.createWriteStream(saveTo));
    const readStream = fs.createReadStream(saveTo);
    readStream.fieldname = fieldname
    readStream.filename = filename
    readStream.transferEncoding = readStream.encoding = encoding
    readStream.mimeType = readStream.mime = mimetype;
    files.push(readStream);
}
```
then it work.

is it a bug or there is anyother reason why you code such as?

**Comment by m4nuC** [comment]
Hi, I apologise for the late reply and thank you for reporting!

There is a reason why wait for `open` event. See https://github.com/m4nuC/async-busboy/issues/1

I will make some testing the next few days. Otherwise you are welcome to submit a PR.

**Comment by m4nuC** [comment]
Fixed with https://github.com/m4nuC/async-busboy/pull/4
