### ISSUE TITLE
Cleanup function will not remove custom onFile function, memory leak

### ISSUE THREAD

**Issue by Bodasia** [m4nuC/async-busboy#37]
async-busyboy doesn't unsubscribe from custom onFile function on error.

**Comment by Bodasia** [comment]
add listener https://github.com/m4nuC/async-busboy/blob/4f2776b5783c79750fe9e21c4b5fb49afcf75e2a/index.js#L25
and here listener are not removed https://github.com/m4nuC/async-busboy/blob/4f2776b5783c79750fe9e21c4b5fb49afcf75e2a/index.js#L78

**Comment by Bodasia** [comment]
solution https://github.com/m4nuC/async-busboy/pull/38

**Comment by Bodasia** [comment]
@fireyy,maybe you

**Comment by m4nuC** [comment]
Thanks @Bodasia. I've pushed the fix on version 1.0.0
